### ISSUE TITLE
OOps

### ISSUE THREAD

**Issue by shubolab** [golang-infrastructure/go-pointer#4]
![image](https://user-images.githubusercontent.com/41125338/203579330-cb878d90-f132-4744-88d6-23a34ea2e3a1.png)

**Comment by CC11001100** [comment]
啊哈哈依赖了私有库，还没写完，写完make public...

**Comment by songzhibin97** [comment]
@ShuBo6  质检员啊 哈哈

**Comment by CC11001100** [comment]
那个库没写完，但先make public了，应该是可以拉取了...
